const { EmbedBuilder } = require('discord.js');
const { formatFinding } = require('./findingFormatter');

function summarizeSeverities(findings = []) {
  const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const finding of findings) {
    if (Object.prototype.hasOwnProperty.call(counts, finding.severity)) {
      counts[finding.severity] += 1;
    }
  }
  return Object.entries(counts)
    .map(([severity, count]) => `${severity}: ${count}`)
    .join(' | ');
}

function buildReportEmbed({ title = 'Driftwatch Report', riskScore = 0, findings = [], summary }) {
  const topFindings = findings.slice(0, 5).map(formatFinding).join('\n') || 'No findings generated by this placeholder run.';

  return new EmbedBuilder()
    .setTitle(title)
    .setDescription(summary || 'Authorized defensive audit summary.')
    .addFields(
      { name: 'Risk score', value: String(riskScore), inline: true },
      { name: 'Severity summary', value: summarizeSeverities(findings), inline: false },
      { name: 'Top findings', value: topFindings.slice(0, 1024), inline: false }
    )
    .setFooter({ text: 'Driftwatch v0.1 scaffold - safeToAutoFix is false' })
    .setTimestamp(new Date());
}

module.exports = { buildReportEmbed, summarizeSeverities };
